In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras import Sequential
from keras.layers import Dense

In [2]:
data=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [16]:
ann=Sequential()

ann.add(Dense(2,activation='linear',input_dim=2))
ann.add(Dense(1,activation='linear'))

In [7]:
X=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [22]:
ann.compile(loss='mean_squared_error',optimizer='adam')

In [17]:
ann.get_weights()

[array([[-0.29662114,  0.14447963],
        [ 0.9257997 ,  0.24120581]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.0619944],
        [0.3487985]], dtype=float32),
 array([0.], dtype=float32)]

In [18]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
            np.array([0.,0.],dtype=np.float32),
            np.array([[0.1],[0.1]],dtype=np.float32),
            np.array([0.],dtype=np.float32)]

In [19]:
ann.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 2)                 6         
                                                                 
 dense_4 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [20]:
ann.set_weights(new_weights)

In [25]:
ann.fit(X,y,epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 26ms/step - loss: 16.0581
Epoch 2/500
1/1 [==============================] - 0s 16ms/step - loss: 15.9212
Epoch 3/500
1/1 [==============================] - 0s 15ms/step - loss: 15.7843
Epoch 4/500
1/1 [==============================] - 0s 18ms/step - loss: 15.6473
Epoch 5/500
1/1 [==============================] - 0s 13ms/step - loss: 15.5104
Epoch 6/500
1/1 [==============================] - 0s 8ms/step - loss: 15.3735
Epoch 7/500
1/1 [==============================] - 0s 12ms/step - loss: 15.2366
Epoch 8/500
1/1 [==============================] - 0s 9ms/step - loss: 15.0998
Epoch 9/500
1/1 [==============================] - 0s 19ms/step - loss: 14.9631
Epoch 10/500
1/1 [==============================] - 0s 8ms/step - loss: 14.8264
Epoch 11/500
1/1 [==============================] - 0s 11ms/step - loss: 14.6899
Epoch 12/500
1/1 [==============================] - 0s 8ms/step - loss: 14.5535
Epoch 13/500
1/1 [=======================

1/1 [==============================] - 0s 9ms/step - loss: 1.1755
Epoch 206/500
1/1 [==============================] - 0s 9ms/step - loss: 1.1689
Epoch 207/500
1/1 [==============================] - 0s 10ms/step - loss: 1.1625
Epoch 208/500
1/1 [==============================] - 0s 9ms/step - loss: 1.1562
Epoch 209/500
1/1 [==============================] - 0s 7ms/step - loss: 1.1502
Epoch 210/500
1/1 [==============================] - 0s 7ms/step - loss: 1.1444
Epoch 211/500
1/1 [==============================] - 0s 7ms/step - loss: 1.1388
Epoch 212/500
1/1 [==============================] - 0s 8ms/step - loss: 1.1333
Epoch 213/500
1/1 [==============================] - 0s 8ms/step - loss: 1.1280
Epoch 214/500
1/1 [==============================] - 0s 8ms/step - loss: 1.1229
Epoch 215/500
1/1 [==============================] - 0s 7ms/step - loss: 1.1180
Epoch 216/500
1/1 [==============================] - 0s 8ms/step - loss: 1.1132
Epoch 217/500
1/1 [==============================] - 

1/1 [==============================] - 0s 7ms/step - loss: 0.9179
Epoch 410/500
1/1 [==============================] - 0s 9ms/step - loss: 0.9174
Epoch 411/500
1/1 [==============================] - 0s 7ms/step - loss: 0.9169
Epoch 412/500
1/1 [==============================] - 0s 7ms/step - loss: 0.9164
Epoch 413/500
1/1 [==============================] - 0s 8ms/step - loss: 0.9159
Epoch 414/500
1/1 [==============================] - 0s 7ms/step - loss: 0.9154
Epoch 415/500
1/1 [==============================] - 0s 14ms/step - loss: 0.9149
Epoch 416/500
1/1 [==============================] - 0s 9ms/step - loss: 0.9144
Epoch 417/500
1/1 [==============================] - 0s 8ms/step - loss: 0.9139
Epoch 418/500
1/1 [==============================] - 0s 8ms/step - loss: 0.9134
Epoch 419/500
1/1 [==============================] - 0s 9ms/step - loss: 0.9129
Epoch 420/500
1/1 [==============================] - 0s 7ms/step - loss: 0.9124
Epoch 421/500
1/1 [==============================] - 

In [30]:
ann.predict([[6,10]])

1/1 [==============================] - 0s 100ms/step


array([[5.467633]], dtype=float32)